---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
pages:
- content/projects/kbd75-lubed-gateron-yellows-205g0.md
